name: CI_CD_React_Django_project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Archive project
      run: zip -r react_django.zip . -x "*.git*" "__pycache__/*"

    - name: Copy files to EC2 via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "react_django.zip"
        target: "~/"

    - name: SSH and run Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          rm -rf ~/react_django
          mkdir -p ~/react_django
          unzip -o ~/react_django.zip -d ~/react_django
          cd ~/react_django
          sudo docker compose up -d --build
